### ISSUE TITLE
K8s Dashboard not accessible

### ISSUE THREAD

**Issue by lmiroslaw** [dotnet-architecture/eShopModernizing#5]
According to this [instruction](https://github.com/kubernetes/dashboard/wiki/Accessing-Dashboard---1.7.X-and-above) 

the dashboard should be accessible at 
http://localhost:port/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

In my case it is not accessible at all. 

`kubectl proxy port 8888

`http://localhost:8888/api/v1/namespaces/kube-system/services/https:kubernetes-dashboard:/proxy/

triggers

> Error: 'tls: oversized record received with length 20527'
> Trying to reach: 'https://10.244.0.6:9090/'

and 
> http: TLS handshake error from <myip>:53950: EOF

Has anyone experienced this issue?

**Comment by hbazerbashi** [comment]
Hi,

I had a similar issue, and while read a thread this [comment](https://github.com/Azure/ACS/issues/70#issuecomment-336611649) actually solved my problem. So can you try adding a "/" at the end and try?

**Comment by lmiroslaw** [comment]
it worked. Thanks!

**Comment by eiximenis** [comment]
There are at least two bugs in different versions of k8s that result in the dashboard not accessible using `http://localhost:8001/ui` (which just performs a redirection)

One is solved appending a `/` at the end of the url once redirection is done (afaik happened in k8s 1.7.something)
Another is solved by changing the url section `https:kubernetes-dashboard` by `http:kubernetes-dashboard` (remove the `s`). Afaik this bug was in k8s 1.9.something
